Repository Alpha-e-Um/Backend, pull requests merged in 2024-05, with the labels that each got.

#76 feat: 유저(자신)의 팀 전체 조회
  business/src/main/java/com/example/eumserver/domain/team/TeamRepository.java
  business/src/main/java/com/example/eumserver/domain/team/TeamService.java
  business/src/main/java/com/example/eumserver/domain/user/UserController.java
Labels: 🖥️ feature, Priority High

#81 refactor: 팀 공고 조회 로직 변경 및 필터를 쿼리 파라미터로 받기
  business/src/main/java/com/example/eumserver/domain/announcement/resume/controller/ResumeAnnouncementController.java
  business/src/main/java/com/example/eumserver/domain/announcement/resume/service/ResumeAnnouncementService.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/controller/TeamAnnouncementController.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementFilter.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementRequest.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepository.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/service/TeamAnnouncementService.java
  business/src/main/java/com/example/eumserver/domain/team/announcement/repository/AnnouncementCustomRepositoryImpl.java
  business/src/test/java/com/example/eumserver/domain/announcement/team/controller/TeamAnnouncementControllerTest.java
Labels: 🖥️ feature, 🛠️ refactor, Priority High

#74 feat: #73-팀 공고 column에 region 추가. entity 수정
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/TeamAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementRequest.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementUpdateRequest.java
Labels: 🖥️ feature

#79 feature: 팀 생성 시 로고 넣기 구현
  business/src/main/java/com/example/eumserver/domain/team/Team.java
  business/src/main/java/com/example/eumserver/domain/team/TeamController.java
  business/src/main/java/com/example/eumserver/domain/team/TeamService.java
  business/src/main/java/com/example/eumserver/global/config/S3Config.java
  business/src/main/java/com/example/eumserver/global/converter/MultipartJackson2HttpMessageConverter.java
  business/src/main/java/com/example/eumserver/global/utils/S3Uploader.java
Labels: 🖥️ feature, Priority High

#91 [ALL] 이력서에 기술 스택 추가하는 기능 #88 + 내 정보를 Token에서 받아오는 버그 #75 + API 공통 응답에서 null값 제외 #90
  business/src/main/java/com/example/eumserver/domain/resume/dto/ResumeRequest.java
  business/src/main/java/com/example/eumserver/domain/resume/entity/Resume.java
  business/src/main/java/com/example/eumserver/domain/user/UserController.java
  business/src/main/java/com/example/eumserver/global/dto/ApiResult.java
Labels: 🐛 bug, 💩 chore, 🖥️ feature, ⚙️ setting, 🛠️ refactor, Priority High

#89 fix-feat: 팀 로고 null일 때 처리 및 팀 로고 형식 및 용량 제한
  business/src/main/java/com/example/eumserver/domain/team/TeamService.java
  business/src/main/java/com/example/eumserver/global/error/CustomExceptionHandler.java
  business/src/main/java/com/example/eumserver/global/error/exception/ErrorCode.java
  business/src/main/resources/application.properties
Labels: 🐛 bug, 🖥️ feature, Priority High

#96 feat: 팀 공고 응답에 누락된 필드 추가
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementResponse.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/mapper/TeamAnnouncementMapper.java
Labels: 🖥️ feature, Priority High

#99 feat: 파일 크기 제한 코드 재사용을 위한 어노테이션 구현
  business/src/main/java/com/example/eumserver/domain/team/TeamController.java
  business/src/main/java/com/example/eumserver/global/annotation/MaxFileSize.java
  business/src/main/java/com/example/eumserver/global/config/WebConfig.java
  business/src/main/java/com/example/eumserver/global/interceptor/MaxFileSizeInterceptor.java
  business/src/main/java/com/example/eumserver/global/utils/S3Uploader.java
  business/src/main/resources/application.properties
Labels: 🖥️ feature, Priority High
