Repository Alpha-e-Um/Backend, pull requests merged in 2024-04, with the labels that each got.

#29 feature: #10 이력서 관련 비즈니스 로직 구현 + #5 Docker 컨테이너화
  Dockerfile
  docker-compose.yml
  src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  src/main/java/com/example/eumserver/domain/jwt/PrincipalDetails.java
  src/main/java/com/example/eumserver/domain/oauth2/CustomOAuth2UserService.java
  src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/eumserver/domain/oauth2/attributes/GoogleOAuth2Attributes.java
  src/main/java/com/example/eumserver/domain/resume/Resume.java
  src/main/java/com/example/eumserver/domain/resume/ResumeController.java
  src/main/java/com/example/eumserver/domain/resume/ResumeMapper.java
  src/main/java/com/example/eumserver/domain/resume/ResumeRepository.java
  src/main/java/com/example/eumserver/domain/resume/ResumeService.java
  src/main/java/com/example/eumserver/domain/resume/dto/ResumeActivityRequest.java
  src/main/java/com/example/eumserver/domain/resume/dto/ResumeCareerRequest.java
  src/main/java/com/example/eumserver/domain/resume/dto/ResumeCertificateRequest.java
  src/main/java/com/example/eumserver/domain/resume/dto/ResumeHomepageRequest.java
  src/main/java/com/example/eumserver/domain/resume/dto/ResumeProjectRequest.java
  src/main/java/com/example/eumserver/domain/resume/dto/ResumeRequest.java
  src/main/java/com/example/eumserver/domain/resume/entity/HomepageType.java
  src/main/java/com/example/eumserver/domain/resume/entity/Resume.java
  src/main/java/com/example/eumserver/domain/resume/entity/ResumeActivity.java
  src/main/java/com/example/eumserver/domain/resume/entity/ResumeCareer.java
  src/main/java/com/example/eumserver/domain/resume/entity/ResumeCertificate.java
  src/main/java/com/example/eumserver/domain/resume/entity/ResumeHomepage.java
  src/main/java/com/example/eumserver/domain/resume/entity/ResumeProject.java
  src/main/java/com/example/eumserver/domain/team/TeamController.java
  src/main/java/com/example/eumserver/domain/team/TeamMapper.java
  src/main/java/com/example/eumserver/domain/team/TeamRepository.java
  src/main/java/com/example/eumserver/domain/team/TeamService.java
  src/main/java/com/example/eumserver/domain/team/dto/TeamRequest.java
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantId.java
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantRepository.java
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantRole.java
  src/main/java/com/example/eumserver/domain/user/Name.java
  src/main/java/com/example/eumserver/domain/user/User.java
  src/main/java/com/example/eumserver/domain/user/UserController.java
  src/main/java/com/example/eumserver/domain/user/UserMapper.java
  src/main/java/com/example/eumserver/domain/user/UserService.java
  src/main/java/com/example/eumserver/domain/user/dto/UserResponse.java
  src/main/java/com/example/eumserver/global/config/SecurityConfig.java
  src/main/java/com/example/eumserver/global/entity/TimeStamp.java
  src/main/java/com/example/eumserver/global/error/exception/EntityNotFoundException.java
  src/main/resources/application.properties
Labels: enhancement, setting

#32 feature: redirect-uri 적용 및 테스트
  .env.example
  src/main/java/com/example/eumserver/global/config/SecurityConfig.java
  src/main/resources/application-oauth.properties
Labels: enhancement, deploy, Priority High

#34 Feature/#24,#26,#27/Nginx설정, SSL인증서 설정, Docker-compose를 통한 배포 환경 구축
  .env.example
  Dockerfile
  build.gradle
  docker-compose.yml
  dump.rdb
  env.sh
  nginx/Dockerfile
  nginx/nginx.conf
  src/main/java/com/example/eumserver/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  src/main/java/com/example/eumserver/domain/oauth2/AuthController.java
  src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/eumserver/domain/oauth2/dto/TokenResponse.java
  src/main/java/com/example/eumserver/domain/oauth2/service/AuthService.java
  src/main/java/com/example/eumserver/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/eumserver/global/config/RedisConfig.java
  src/main/java/com/example/eumserver/global/config/SecurityConfig.java
  src/main/java/com/example/eumserver/global/error/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/eumserver/global/utils/CookieUtils.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
Labels: setting

#35 feature: logout 기능 구현
  src/main/java/com/example/eumserver/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  src/main/java/com/example/eumserver/domain/oauth2/AuthController.java
  src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/eumserver/domain/oauth2/service/AuthService.java
  src/main/java/com/example/eumserver/global/utils/CookieUtils.java
  src/main/resources/application.properties
Labels: bug, enhancement, Priority Middle

#38 fix: Embedded Id에 누락된 함수 재정의
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantId.java
Labels: bug

#40 fix: add @EqualsAndHashCode (#37)
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantId.java
Labels: enhancement

#41 feature: 팀 공고 API 구현 및 테스트 코드 작성
  .gitignore
  build.gradle
  src/main/java/com/example/eumserver/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  src/main/java/com/example/eumserver/domain/oauth2/AuthController.java
  src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/eumserver/domain/oauth2/service/AuthService.java
  src/main/java/com/example/eumserver/domain/team/Team.java
  src/main/java/com/example/eumserver/domain/team/announcement/controller/AnnouncementController.java
  src/main/java/com/example/eumserver/domain/team/announcement/domain/Announcement.java
  src/main/java/com/example/eumserver/domain/team/announcement/domain/OccupationClassification.java
  src/main/java/com/example/eumserver/domain/team/announcement/domain/RecruitmentTypes.java
  src/main/java/com/example/eumserver/domain/team/announcement/dto/AnnouncementFilter.java
  src/main/java/com/example/eumserver/domain/team/announcement/dto/AnnouncementRequest.java
  src/main/java/com/example/eumserver/domain/team/announcement/dto/AnnouncementResponse.java
  src/main/java/com/example/eumserver/domain/team/announcement/dto/AnnouncementUpdateRequest.java
  src/main/java/com/example/eumserver/domain/team/announcement/mapper/AnnouncementMapper.java
  src/main/java/com/example/eumserver/domain/team/announcement/repository/AnnouncementCustomRepository.java
  src/main/java/com/example/eumserver/domain/team/announcement/repository/AnnouncementCustomRepositoryImpl.java
  src/main/java/com/example/eumserver/domain/team/announcement/repository/AnnouncementRepository.java
  src/main/java/com/example/eumserver/domain/team/announcement/service/AnnouncementService.java
  src/main/java/com/example/eumserver/global/config/QuerydslConfig.java
  src/main/java/com/example/eumserver/global/utils/CookieUtils.java
  src/main/resources/application.properties
  src/test/java/com/example/eumserver/BaseIntegrationTest.java
  src/test/java/com/example/eumserver/EumServerApplicationTests.java
  src/test/java/com/example/eumserver/domain/team/announcement/controller/AnnouncementControllerTest.java
  src/test/resources/application.properties
Labels: enhancement
