Repository Alpha-e-Um/Backend, pull requests merged in 2024-06, with the labels that each got.

#105 feat: 팀 응답에 소유 여부 포함하기 (#102)
  business/src/main/java/com/example/eumserver/domain/team/Team.java
  business/src/main/java/com/example/eumserver/domain/team/TeamMapper.java
  business/src/main/java/com/example/eumserver/domain/team/TeamService.java
  business/src/main/java/com/example/eumserver/domain/team/dto/TeamRequest.java
  business/src/main/java/com/example/eumserver/domain/team/dto/TeamResponse.java
  business/src/main/java/com/example/eumserver/domain/team/invite/InviteService.java
  business/src/main/java/com/example/eumserver/domain/team/repository/TeamRepository.java
  business/src/main/java/com/example/eumserver/domain/user/UserController.java
Labels: 🖥️ feature, Priority High

#108 feat: 지역 및 MBTI enum 처리 (#97)
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/TeamAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementRequest.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementResponse.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementUpdateRequest.java
  business/src/main/java/com/example/eumserver/domain/application/entity/TeamApplication.java
  business/src/main/java/com/example/eumserver/domain/application/service/ApplicationService.java
  business/src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  business/src/main/java/com/example/eumserver/domain/jwt/PrincipalDetails.java
  business/src/main/java/com/example/eumserver/domain/oauth2/service/CustomOAuth2UserService.java
  business/src/main/java/com/example/eumserver/domain/resume/ResumeService.java
  business/src/main/java/com/example/eumserver/domain/resume/entity/Resume.java
  business/src/main/java/com/example/eumserver/domain/team/TeamService.java
  business/src/main/java/com/example/eumserver/domain/team/invite/InviteService.java
  business/src/main/java/com/example/eumserver/domain/team/participant/Participant.java
  business/src/main/java/com/example/eumserver/domain/user/CustomUsserDetailService.java
  business/src/main/java/com/example/eumserver/domain/user/UserController.java
  business/src/main/java/com/example/eumserver/domain/user/UserMapper.java
  business/src/main/java/com/example/eumserver/domain/user/UserRepository.java
  business/src/main/java/com/example/eumserver/domain/user/UserService.java
  business/src/main/java/com/example/eumserver/domain/user/domain/MBTI.java
  business/src/main/java/com/example/eumserver/domain/user/domain/Name.java
  business/src/main/java/com/example/eumserver/domain/user/domain/User.java
  business/src/main/java/com/example/eumserver/domain/user/dto/UserResponse.java
  business/src/main/java/com/example/eumserver/domain/user/dto/UserUpdateRequest.java
  business/src/main/java/com/example/eumserver/global/domain/Region.java
  business/src/test/java/com/example/eumserver/domain/resume/ResumeControllerTest.java
Labels: 🖥️ feature, Priority High

#112 fix: 이력서 공고 조회 실패 해결 및 파라미터 제어 (#110)
  business/src/main/java/com/example/eumserver/domain/announcement/resume/controller/ResumeAnnouncementController.java
  business/src/main/java/com/example/eumserver/domain/announcement/resume/dto/ResumeAnnouncementFilter.java
  business/src/main/java/com/example/eumserver/domain/announcement/resume/repository/ResumeAnnouncementCustomRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/announcement/resume/service/ResumeAnnouncementService.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/service/TeamAnnouncementService.java
Labels: 🐛 bug, Priority High

#114 feat: 팀 참가자 정보 조회 구현 (#111)
  business/src/main/java/com/example/eumserver/domain/team/TeamController.java
  business/src/main/java/com/example/eumserver/domain/team/participant/ParticipantRepository.java
  business/src/main/java/com/example/eumserver/domain/team/participant/ParticipantService.java
Labels: 🖥️ feature, Priority High

#115 feat: 성 및 이름으로 쪼개기 (#16)
  business/src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  business/src/main/java/com/example/eumserver/domain/jwt/PrincipalDetails.java
  business/src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationSuccessHandler.java
  business/src/main/java/com/example/eumserver/domain/oauth2/attributes/GoogleOAuth2Attributes.java
  business/src/main/java/com/example/eumserver/domain/oauth2/attributes/OAuth2Attributes.java
  business/src/main/java/com/example/eumserver/domain/oauth2/service/CustomOAuth2UserService.java
  business/src/main/java/com/example/eumserver/domain/user/CustomUsserDetailService.java
  business/src/main/java/com/example/eumserver/domain/user/domain/Name.java
  business/src/main/java/com/example/eumserver/domain/user/domain/User.java
Labels: 🖥️ feature, Priority High

#116 [FEATURE] 조회수 기능 구현하기 #92
  business/src/main/java/com/example/eumserver/EumServerApplication.java
  business/src/main/java/com/example/eumserver/domain/announcement/resume/repository/ResumeAnnouncementCustomRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/controller/TeamAnnouncementController.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/TeamAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementDetailResponse.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/mapper/TeamAnnouncementMapper.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepository.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/service/TeamAnnouncementService.java
  business/src/main/java/com/example/eumserver/domain/jwt/JwtAuthenticationFilter.java
  business/src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  business/src/main/java/com/example/eumserver/domain/oauth2/AuthController.java
  business/src/main/java/com/example/eumserver/domain/post/Post.java
  business/src/main/java/com/example/eumserver/domain/post/PostRepository.java
  business/src/main/java/com/example/eumserver/domain/post/PostService.java
  business/src/main/java/com/example/eumserver/global/config/RedisConfig.java
  business/src/main/java/com/example/eumserver/global/utils/RedisUtil.java
  business/src/test/java/com/example/eumserver/domain/application/controller/TeamApplicationControllerTest.java
Labels: 🖥️ feature, ⚙️ setting

#120 feat: 팀 공고 응답에 팀 이름 추가 및 성능 개선 (#103)
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementResponse.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/mapper/TeamAnnouncementMapper.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepositoryImpl.java
  business/src/test/java/com/example/eumserver/domain/announcement/team/controller/TeamAnnouncementControllerTest.java
Labels: 🖥️ feature, 🔴 priority high

#124 feat: #123-팀 공고 테이블 summary 컬럼 추가
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/TeamAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementDetailResponse.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementRequest.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementResponse.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementUpdateRequest.java
Labels: 🖥️ feature

#121 feat: CustomException message 추가 (#113)
  business/src/main/java/com/example/eumserver/global/dto/ApiResult.java
  business/src/main/java/com/example/eumserver/global/error/CustomExceptionHandler.java
Labels: 🐛 bug, 🔴 priority high

#122 feat: 팀 공고 지원 수락 및 거절 구현
  business/src/main/java/com/example/eumserver/domain/announcement/team/controller/TeamAnnouncementController.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/TeamAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementResponse.java
  business/src/main/java/com/example/eumserver/domain/application/dto/MyApplicationFilterRequest.java
  business/src/main/java/com/example/eumserver/domain/application/dto/MyApplicationResponse.java
  business/src/main/java/com/example/eumserver/domain/application/mapper/ApplicationMapper.java
  business/src/main/java/com/example/eumserver/domain/application/repository/ApplicationCustomRepository.java
  business/src/main/java/com/example/eumserver/domain/application/repository/ApplicationRepository.java
  business/src/main/java/com/example/eumserver/domain/application/service/ApplicationService.java
  business/src/main/java/com/example/eumserver/domain/application/team/controller/TeamApplicationController.java
  business/src/main/java/com/example/eumserver/domain/application/team/dto/MyTeamApplicationFilterRequest.java
  business/src/main/java/com/example/eumserver/domain/application/team/dto/MyTeamApplicationResponse.java
  business/src/main/java/com/example/eumserver/domain/application/team/entity/TeamApplication.java
  business/src/main/java/com/example/eumserver/domain/application/team/entity/TeamApplicationState.java
  business/src/main/java/com/example/eumserver/domain/application/team/mapper/TeamApplicationMapper.java
  business/src/main/java/com/example/eumserver/domain/application/team/repository/TeamApplicationCustomRepository.java
  business/src/main/java/com/example/eumserver/domain/application/team/repository/TeamApplicationRepository.java
  business/src/main/java/com/example/eumserver/domain/application/team/repository/TeamApplicationRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/application/team/service/ApplicationService.java
  business/src/main/java/com/example/eumserver/domain/resume/ResumeController.java
  business/src/main/java/com/example/eumserver/domain/user/domain/User.java
  business/src/main/java/com/example/eumserver/global/error/exception/ErrorCode.java
Labels: 🖥️ feature, 🔴 priority high

#128 [FEATURE] 글을 조건에 따라서 보여주는 필터 추가 #93 + Pagination 필요 없는 정보 정리 #125
  business/src/main/java/com/example/eumserver/domain/announcement/team/controller/TeamAnnouncementController.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/ScoredAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/TeamAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementFilter.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/dto/TeamAnnouncementResponseWrapper.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/mapper/TeamAnnouncementMapper.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepository.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/service/TeamAnnouncementService.java
  business/src/main/java/com/example/eumserver/domain/post/Post.java
  business/src/main/java/com/example/eumserver/domain/post/PostRepository.java
  business/src/main/java/com/example/eumserver/domain/post/PostSortingOption.java
  business/src/main/java/com/example/eumserver/domain/post/ScoredPost.java
  business/src/main/java/com/example/eumserver/domain/post/strategy/LatestSortingStrategy.java
  business/src/main/java/com/example/eumserver/domain/post/strategy/PopularSortingStrategy.java
  business/src/main/java/com/example/eumserver/domain/post/strategy/SortingStrategy.java
  business/src/main/java/com/example/eumserver/domain/post/strategy/SortingStrategyFactory.java
  business/src/main/java/com/example/eumserver/domain/post/strategy/ViewsSortingStrategy.java
Labels: 🗒️ documentation, 🖥️ feature, ❔ question, ⚙️ setting, 🛠️ refactor

#127 fix: 구글 로그인 새로하면 정보 새로 업데이트 되는거 막음
  business/src/main/java/com/example/eumserver/domain/oauth2/service/CustomOAuth2UserService.java
  business/src/main/java/com/example/eumserver/domain/user/domain/User.java
Labels: 🐛 bug, 🔴 priority high

#131 fix: TeamApplication import 문제 해결
  business/src/main/java/com/example/eumserver/domain/user/domain/User.java
Labels: 🐛 bug, 🔴 priority high

#134 [FIX] expired 필터링 오류 수정 (#133)
  business/src/main/java/com/example/eumserver/domain/announcement/team/repository/TeamAnnouncementCustomRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/post/PostSortingOption.java
Labels: 🐛 bug, 🔴 priority high

#139 feat: docker-compose-local.yml 제작 (#135)
  docker-compose-local.yml
  test-compose.yml
Labels: 🖥️ feature, ⚙️ setting, 🟢 priority middle

#143 [FIX] 이력서 SoftDelete로 변경 #138 + 이력서 홈페이지 url만 받도록 변경 #137
  business/src/main/java/com/example/eumserver/domain/announcement/resume/service/ResumeAnnouncementService.java
  business/src/main/java/com/example/eumserver/domain/announcement/team/domain/TeamAnnouncement.java
  business/src/main/java/com/example/eumserver/domain/application/team/entity/TeamApplication.java
  business/src/main/java/com/example/eumserver/domain/application/team/service/ApplicationService.java
  business/src/main/java/com/example/eumserver/domain/resume/ResumeService.java
  business/src/main/java/com/example/eumserver/domain/resume/dto/ResumeHomepageRequest.java
  business/src/main/java/com/example/eumserver/domain/resume/entity/ResumeHomepage.java
  business/src/main/java/com/example/eumserver/domain/resume/repository/ResumeCustomRepository.java
  business/src/main/java/com/example/eumserver/domain/resume/repository/ResumeCustomRepositoryImpl.java
  business/src/main/java/com/example/eumserver/domain/resume/repository/ResumeRepository.java
  business/src/main/java/com/example/eumserver/global/dto/TimeStamp.java
Labels: 🐛 bug, 💩 chore, 🖥️ feature, 🛠️ refactor
