Repository Alpha-e-Um/Backend, pull requests merged in 2024-03, with the labels that each got.

#4 feat: implement Google OAuth2 with error handling
  .env.example
  .gitignore
  build.gradle
  src/main/java/com/example/eumserver/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/eumserver/domain/jwt/JwtTokenInvalidException.java
  src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  src/main/java/com/example/eumserver/domain/jwt/PrincipleDetails.java
  src/main/java/com/example/eumserver/domain/oauth2/CustomOAuth2UserService.java
  src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/eumserver/domain/oauth2/attributes/GoogleOAuth2Attributes.java
  src/main/java/com/example/eumserver/domain/oauth2/attributes/OAuth2Attributes.java
  src/main/java/com/example/eumserver/domain/oauth2/attributes/OAuth2AttributesFactory.java
  src/main/java/com/example/eumserver/domain/user/Account.java
  src/main/java/com/example/eumserver/domain/user/User.java
  src/main/java/com/example/eumserver/domain/user/UserController.java
  src/main/java/com/example/eumserver/domain/user/UserMapper.java
  src/main/java/com/example/eumserver/domain/user/UserRepository.java
  src/main/java/com/example/eumserver/domain/user/UserResponse.java
  src/main/java/com/example/eumserver/domain/user/UserService.java
  src/main/java/com/example/eumserver/global/config/SecurityConfig.java
  src/main/java/com/example/eumserver/global/error/CustomAccessDeniedHandler.java
  src/main/java/com/example/eumserver/global/error/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/eumserver/global/error/CustomException.java
  src/main/java/com/example/eumserver/global/error/CustomExceptionHandler.java
  src/main/java/com/example/eumserver/global/error/ErrorResponse.java
  src/main/java/com/example/eumserver/global/utils/CookieUtils.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
Labels: enhancement

#7 feat : My Info Modify API
  build.gradle
  src/main/java/com/example/eumserver/domain/jwt/JwtTokenProvider.java
  src/main/java/com/example/eumserver/domain/jwt/PrincipleDetails.java
  src/main/java/com/example/eumserver/domain/model/Name.java
  src/main/java/com/example/eumserver/domain/oauth2/CustomOAuth2UserService.java
  src/main/java/com/example/eumserver/domain/oauth2/attributes/GoogleOAuth2Attributes.java
  src/main/java/com/example/eumserver/domain/resume/Resume.java
  src/main/java/com/example/eumserver/domain/team/Team.java
  src/main/java/com/example/eumserver/domain/user/User.java
  src/main/java/com/example/eumserver/domain/user/UserController.java
  src/main/java/com/example/eumserver/domain/user/UserMapper.java
  src/main/java/com/example/eumserver/domain/user/UserResponse.java
  src/main/java/com/example/eumserver/domain/user/UserService.java
  src/main/java/com/example/eumserver/domain/user/dto/UserResponse.java
  src/main/java/com/example/eumserver/domain/user/dto/UserUpdateRequest.java
  src/main/java/com/example/eumserver/global/config/SecurityConfig.java
  src/main/java/com/example/eumserver/global/config/SwaggerConfig.java
  src/main/resources/static/favicon.ico
  src/test/java/com/example/eumserver/domain/user/UserControllerTest.java
Labels: enhancement, setting

#9 feat: social login test 이후 redirect url 및 cors setting
  src/main/java/com/example/eumserver/domain/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/eumserver/global/config/SecurityConfig.java
  src/main/java/com/example/eumserver/global/config/WebConfig.java
Labels: enhancement

#15 feat: Team 관련 로직 및 API 설계
  src/main/java/com/example/eumserver/domain/team/Team.java
  src/main/java/com/example/eumserver/domain/team/TeamController.java
  src/main/java/com/example/eumserver/domain/team/TeamMapper.java
  src/main/java/com/example/eumserver/domain/team/TeamRepository.java
  src/main/java/com/example/eumserver/domain/team/TeamService.java
  src/main/java/com/example/eumserver/domain/team/dto/TeamRequest.java
  src/main/java/com/example/eumserver/domain/team/participant/Participant.java
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantId.java
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantRepository.java
  src/main/java/com/example/eumserver/domain/team/participant/ParticipantRole.java
  src/main/java/com/example/eumserver/domain/user/User.java
  src/main/java/com/example/eumserver/global/config/SecurityConfig.java
  src/main/java/com/example/eumserver/global/error/exception/CustomException.java
  src/main/java/com/example/eumserver/global/error/exception/EntityNotFoundException.java
  src/main/resources/application.properties
Labels: documentation, enhancement
